<a href="https://colab.research.google.com/github/Null3rror/OpenAI-Gym/blob/master/FrozenLake_v0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# install dependancies, takes around 45 seconds

Rendering Dependancies


In [1]:
#remove " > /dev/null 2>&1" to see what is going on under the hood
!pip install gym pyvirtualdisplay > /dev/null 2>&1
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1

In [2]:
!apt-get update > /dev/null 2>&1
!apt-get install cmake > /dev/null 2>&1
!pip install --upgrade setuptools 2>&1
!pip install ez_setup > /dev/null 2>&1
# !pip install gym[atari] > /dev/null 2>&1

In [3]:
import gym
from gym import logger as gymlogger
from gym.wrappers import Monitor
gymlogger.set_level(40) #error only
import tensorflow as tf
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import math
import glob
import io
import base64
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import HTML, clear_output

from IPython import display as ipythondisplay

In [4]:
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

In [5]:
def query_environment(name):
  env = gym.make(name)
  spec = gym.spec(name)
  print(f"Action Space: {env.action_space}")
  print(f"Observation Space: {env.observation_space}")
  print(f"Max Episode Steps: {spec.max_episode_steps}")
  print(f"Nondeterministic: {spec.nondeterministic}")
  print(f"Reward Range: {env.reward_range}")
  print(f"Reward Threshold: {spec.reward_threshold}")
  return env

# FrozenLake-v0!

In [6]:
def actions_to_letters(actions):
    res = []
    for a in actions:
        if a == 0:
            res.append("L")
        elif a == 1:
            res.append("D")    
        elif a == 2:
            res.append("R")   
        elif a == 3:
            res.append("U") 
  
    return np.array(res)

In [7]:
env = query_environment("FrozenLake-v0")

Action Space: Discrete(4)
Observation Space: Discrete(16)
Max Episode Steps: 100
Nondeterministic: False
Reward Range: (0, 1)
Reward Threshold: 0.78


In [264]:
alpha = 0.3
epsilon_max = 1
epsilon = 1
epsilon_min = 0.01
epsilon_decay_rate = 0.005
discount = 0.99
max_step_count = 100

episodes = 15000

In [265]:
num_reached_goals = 0
num_reached_holes = 0
Q = np.zeros((env.observation_space.n, env.action_space.n))
for i in range(1, episodes):
  observation = env.reset()
  np.random.seed(i)
  step_count = 0
  while True:
    # env.render()
    probability = random.uniform(0, 1)
    if probability <= epsilon:
      action = env.action_space.sample() 
    else:
      action = np.argmax(Q[observation])

    next_observation, reward, done, info = env.step(action) 

    q = Q[observation, action] 
    Q[observation, action] = q + alpha * (reward + discount * np.max(Q[next_observation]) - q)

    observation = next_observation
    step_count += 1

    if done: 
      # clear_output(wait=True)
      if reward == 1:
        num_reached_goals += 1
      else:
        num_reached_holes += 1
      break
    if step_count >= max_step_count:
      break
  t = np.exp(-epsilon_decay_rate * i)
  epsilon = epsilon_min * (1 - t) + epsilon_max * t
  # print(epsilon)
  if i % 100 == 0:
    clear_output(wait=True)
    print(epsilon)
    print(f"Epoch: {i}")
  

0.01
Epoch: 14900


In [266]:
print(Q)
print(num_reached_goals)
print(num_reached_holes)
print(num_reached_goals / (num_reached_holes + num_reached_goals))

[[0.51385859 0.5141297  0.50593197 0.49454605]
 [0.34906971 0.26177617 0.26201747 0.50686902]
 [0.35913497 0.38302029 0.35303532 0.48181766]
 [0.30480433 0.29681473 0.23288505 0.47048341]
 [0.51699368 0.51259636 0.22211197 0.4562173 ]
 [0.         0.         0.         0.        ]
 [0.08261719 0.00605706 0.15776746 0.02424281]
 [0.         0.         0.         0.        ]
 [0.45732733 0.38485004 0.49330462 0.53822737]
 [0.27145131 0.59668122 0.40492394 0.23371287]
 [0.44572738 0.27094957 0.37039519 0.21530634]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53494633 0.35658379 0.75225078 0.53992816]
 [0.7075193  0.93888788 0.61749719 0.61990643]
 [0.         0.         0.         0.        ]]
9440
5559
0.6293752916861124


In [267]:
observation = env.reset()

while True:  
    env.render()

    action = np.argmax(Q[observation])
    #your agent goes here
    
         
    observation, reward, done, info = env.step(action) 
   
    if done: 
      env.render()
      break;
            
env.close()


SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
