<a href="https://colab.research.google.com/github/Null3rror/OpenAI-Gym/blob/master/Toy%20text/Taxi_v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# install dependancies, takes around 45 seconds

Rendering Dependancies


In [ ]:
#remove " > /dev/null 2>&1" to see what is going on under the hood
!pip install gym pyvirtualdisplay > /dev/null 2>&1
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1

In [ ]:
!apt-get update > /dev/null 2>&1
!apt-get install cmake > /dev/null 2>&1
!pip install --upgrade setuptools 2>&1
!pip install ez_setup > /dev/null 2>&1
# !pip install gym[atari] > /dev/null 2>&1

In [ ]:
import gym
from gym import logger as gymlogger
from gym.wrappers import Monitor
gymlogger.set_level(40) #error only
import tensorflow as tf
import numpy as np
import random
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import math
import glob
import io
import base64
from IPython.display import HTML

from IPython import display as ipythondisplay

In [ ]:
from pyvirtualdisplay import Display
display = Display(visible=0, size=(1400, 900))
display.start()

In [ ]:
def query_environment(name):
  env = gym.make(name)
  spec = gym.spec(name)
  print(f"Action Space: {env.action_space}")
  print(f"Observation Space: {env.observation_space}")
  print(f"Max Episode Steps: {spec.max_episode_steps}")
  print(f"Nondeterministic: {spec.nondeterministic}")
  print(f"Reward Range: {env.reward_range}")
  print(f"Reward Threshold: {spec.reward_threshold}")
  return env

# Taxi-v3!

In [ ]:
env = query_environment("Taxi-v3")

Action Space: Discrete(6)
Observation Space: Discrete(500)
Max Episode Steps: 200
Nondeterministic: False
Reward Range: (-inf, inf)
Reward Threshold: 8


In [ ]:
alpha = 0.1
epsilon = 1
gamma = 0.95

Q = np.zeros((env.observation_space.n, env.action_space.n))
epochs = 10000

In [ ]:
for i in range(1, 10000):
  num_of_penalties = 0
  observation = env.reset()
  frames = [] 
  epsilon = 0.1 if i != 1 else 1

  while True:
    probability = random.uniform(0, 1)
    if probability <= epsilon:
      action = env.action_space.sample() 
    else:
      action = np.argmax(Q[observation])

    next_observation, reward, done, info = env.step(action) 

    t = (reward + gamma * np.max(Q[next_observation]))
    Q[observation, action] = (1 - alpha) * Q[observation, action] + alpha * t

    observation = next_observation
    num_of_penalties += 1 if reward == -10 else 0
    epsilon *= 0.9;


    if done: break

  if i % 100 == 0:
    clear_output(wait=True)
    print(f"Epoch: {i}")
  

Epoch: 9900


In [ ]:
print(Q)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 2.75200125  3.94947709  2.75199962  3.94947573  5.20997639 -5.05052265]
 [ 7.93349065  9.40367435  7.93348925  9.40367269 10.9512375   0.4036749 ]
 ...
 [ 6.01377213 12.58007677  7.65879495  4.79845388 -0.8828941  -1.59016988]
 [ 2.83446887  6.53663577  0.99691421  2.98768889 -4.81454539 -4.24663761]
 [ 2.89128654  2.54942503  4.97845323 17.99986497  0.75976392 -1.        ]]


In [ ]:
observation = env.reset()

while True:  
    env.render()

    action = np.argmax(Q[observation])
    #your agent goes here
    
         
    observation, reward, done, info = env.step(action) 
   
    if done: 
      break;
    epsilon *= 0.9;
            
env.close()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : | : : |
| : :_: : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
| :_: : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : | : : |
|_: : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
|_: | : : |
| : : : : |
| | : | : |
|Y| : |B: |
